services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/nodefarm

    ports:
      - '7000:7000'

    env_file:
      - config.env

    environment:
      - NODE_PATH=.
